#!/usr/bin/env bash

pacman -Sy archiso --noconfirm --disable-sandbox

cat << 'EOF' > /usr/share/archiso/configs/baseline/profiledef.sh
iso_name='archiso'
iso_label="ARCHISO-v"$(date '+%d%m%y')""
iso_publisher='Arch Linux <https://archlinux.org>'
iso_application='Arch Linux baseline'
iso_version='v'
install_dir='arch'
buildmodes=('iso')
bootmodes=('uefi-x64.systemd-boot.esp')
arch='x86_64'
pacman_conf="pacman.conf"
airootfs_image_type='erofs'
airootfs_image_tool_options=(
  '-zlzma,level=109,dictsize=8388608:deflate,level=9'
  '-Efragments,dedupe,force-inode-compact,ztailpacking,^xattr-name-filter'
  '-C262144'
  '--workers=0'
  '-b512'
)
bootstrap_tarball_compression=('zstd' '-T0' '--ultra' '-20zc')
file_permissions=(
  ['/etc/shadow']='0:0:400'
)
EOF

cat << 'EOF' > /usr/share/archiso/configs/baseline/packages.x86_64
amd-ucode
base
linux
linux-firmware
gptfdisk
mkinitcpio
mkinitcpio-archiso
python
pv
arch-install-scripts
reflector
btrfs-progs
dosfstools
iwd
EOF

cp /usr/share/archiso/configs/{releng,baseline}/airootfs/etc/passwd
cp /usr/share/archiso/configs/{releng,baseline}/airootfs/etc/shadow
rm -rf /usr/share/archiso/configs/baseline/{syslinux,grub}


mkdir -p ./hui
mount -t tmpfs -o 'noatime,size=2G' tmpfs ./hui
echo '- Building archiso...'
mkarchiso -w ./hui /usr/share/archiso/configs/baseline
