#!/usr/bin/env bash
#
#
set -e
pacman -Sy archiso --noconfirm --disable-sandbox

conf=/baseline
cp -r "/usr/share/archiso/configs/${conf}" .
date=123
cat << 'EOF' > "${conf}/profiledef.sh"
iso_name='archiso'
iso_label="NAME"
iso_publisher='Arch Linux <https://archlinux.org>'
iso_application='Arch Linux baseline'
iso_version='v'
install_dir='arch'
buildmodes=('iso')
bootmodes=('uefi-x64.systemd-boot.esp')
arch='x86_64'
pacman_conf="pacman.conf"
airootfs_image_type='erofs'
#'-zlzma,level=109,dictsize=8388608'
#'-zzstd,level=20,dictsize=1048576'
airootfs_image_tool_options=(
  '-zzstd,level=22,dictsize=1048576'
  '-Efragments,dedupe,force-inode-extended,ztailpacking'
  '--workers=4'
  '-T0'
  '-C1048576'
)
bootstrap_tarball_compression=('zstd' '-T0' '--ultra' '-20zc')
EOF
echo 'base' > "${conf}/packages.x86_64"
echo '- Building archiso...'
sed -i 's/5/128/' "$conf/pacman.conf"
mkarchiso -w ./hui "${conf}"
