#!/usr/bin/env bash

pacman -Sy archiso man-db --noconfirm --disable-sandbox
echo '****'
mkarchiso --help
echo '****'
man archiso
echo '****'
man -k mkarchiso
exit

mkarchiso
cat << 'EOF' > /usr/share/archiso/configs/baseline/profiledef.sh
iso_name="archlinux-baseline"
iso_label="ARCH_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
iso_publisher="Arch Linux <https://archlinux.org>"
iso_application="Arch Linux baseline"
#iso_version="$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)"
iso_version=1
install_dir="arch"
buildmodes=('iso')
bootmodes=('uefi-x64.systemd-boot.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"
#airootfs_image_type="erofs"
#airootfs_image_type="squashfs"
airootfs_image_type="ext4"
#airootfs_image_tool_options=('-zzstd,level=20')
#bootstrap_tarball_compression=(zstd -c -T0 --long --ultra -20)
#airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
bootstrap_tarball_compression=(lz4 -1c)
file_permissions=(
  ["/etc/shadow"]="0:0:400"
)
EOF

cat << 'EOF' > /usr/share/archiso/configs/baseline/packages.x86_64
base
linux
linux-firmware
mkinitcpio
mkinitcpio-archiso
zsh
arch-install-scripts
btrfs-progs
dosfstools
iwd
EOF

cp /usr/share/archiso/configs/{releng,baseline}/airootfs/etc/passwd
cp /usr/share/archiso/configs/{releng,baseline}/airootfs/etc/shadow

rm -rf /usr/share/archiso/configs/baseline/{syslinux,grub}
mkarchiso -v /usr/share/archiso/configs/baseline
