name: hui
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: ebat
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: apktool
          version: 1.0

      - name: suka
        run: bash ./hui.sh
