name: name

on:
  schedule:
      - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: jhjhjh
        uses: actions/checkout@v3
        
      - name: ya
        run: bash ./hui.sh
