name: name

on:
  schedule:
      - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: jhjhjh
        uses: actions/checkout@latest
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: apktool
          version: 1.0
      - name: ya
        run: bash ./hui.sh
