name: mkng

# on: workflow_dispatch
on: push

permissions:
  contents: write

jobs:
  cmprsng:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /dev/shm
    steps:
#     - uses: actions/checkout@v4
#        with:
#           set-safe-directory: '/dev/shm'
      - name: hui
        run: |
          ls -lh
          pwd
      - name: mkng n fle
        run: |
          tar -cvf ./.rch-nstll.tar ./*
          zstd --ultra -f20 ./.rch-nstll.tar
      - name: rlsng
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create huy || true
          gh release upload rolling './.rch-nstll.tar.zst' --clobber
