name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: dc
       run: |
         sudo apt update
         sudo apt install xxhash
         dd if=/dev/zero of=z bs=12G count=1 conv=fsync
         dd if=/dev/zero of=z ibs=12G obs=256K count=1 conv=fsync
         time -p xxhsum -H0 ./z
         time -p xxhsum -H1 ./z
         time -p xxhsum -H2 --tag ./z
         time -p xxhsum -H3 ./z