name: mkng

# on: workflow_dispatch
on: push

permissions:
  contents: write

jobs:
  cmprsng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mkng n fle
        run: |
          tar -cvf ./.rch-nstll.tar ./*
          zstd --ultra -f20 ./.rch-nstll.tar
      - name: rlsng
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create hui --notes '' || true
          gh release upload rolling './.rch-nstll.tar.zst' --clobber
