name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          rm -f ./README.md
          a="$(tar -cvf - ./* | lz4 -12zvcf --favor-decSpeed -)"
      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(echo "$a" | sha256sum - | cut -d ' ' -f1)"
          gh release delete rolling --cleanup-tag -y || true
          echo "$a" | gh release create rolling -
