name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete rolling --cleanup-tag -y || true
          echo "#### SHA256 Part:\n\`\`\`$shap\`\`\`\n> $(date)" |\
          gh release create rolling "./123" --generate-notes -F-

