name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: hui
       uses: actions/checkout@v4
     - name: dc
       run: |
         docker pull archlinux
         docker run --name archiso -dt --privileged archlinux:latest
         docker cp ./mkhui.sh archiso:/
         docker exec archiso bash ./mkhui.sh
         docker cp archiso:/var/archiso-v/iso/arch9660.iso .
         gh release delete iso || true
         gh release create iso arch9660.iso
       env:
         GH_TOKEN: ${{ github.token }}
