name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        set +e
        sudo locale-gen --lang 'ru' --lang en --lang
        sudo locale-gen --lang 'ru' --lang en