name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        run: |
          sh --version
          sh --help
