name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        command -v adduser useradd
        file "$(command -v adduser useradd)"
        echo '****'
        cat "$(command -v adduser)"
