name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          dd if=/dev/zero of=./hui bs=4M count=256 conv=fsync
          dd if=/dev/zero of=./hui bs=2M count=512 conv=fsync
          dd if=/dev/zero of=./hui bs=1M count=1024 conv=fsync
          dd if=/dev/zero of=./hui bs=512K count=2048 conv=fsync
          dd if=/dev/zero of=./hui bs=256K count=4096 conv=fsync
          dd if=/dev/zero of=./hui bs=128K count=8192 conv=fsync
          dd if=/dev/zero of=./hui bs=8M count=128 conv=fsync
