name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: ckout
       uses: actions/checkout@v4
     - name: dc
       run: |
         docker pull archlinux
         sudo docker run --name hui --privileged -t archlinux touch hzui
         sudo docker cp hui:/hzui .
     - name: rls
       run: |
         gh release delete iso --cleanup-tag -y || true
         gh release create iso hzu*
       env:
         GH_TOKEN: ${{ github.token }}
