name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          time -p sudo dd if=/dev/zero of=/dev/shm/hui
          time -p sudo dd if=/dev/zero > /dev/shm/hui