name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     #- uses: actions/checkout@v4
     - name: dc
       run: |

         sudo apt update
         sudo apt install lzop

         curl -fZL 'https://download.fedoraproject.org/pub/fedora/linux/releases/41/Server/aarch64/images/Fedora-Server-41-1.4.aarch64.raw.xz' \
           | xz -dvc -T0 -M100% > hui.raw
         file hui.raw

         time lz4 -12zv hui.raw hz.lz4
         sleep 1
         time lzop -12zv hui.raw hoz.lzo
         sleep 1
         
         ls -lh
         echo '****'
         du -h

         time lz4 --favor-decSpeed -df hz.lz4
         sleep 1
         time lzop -df hoz.lzo