name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: ckout
       uses: actions/checkout@v4
     - name: dc
       run: |
         docker pull archlinux
         sudo docker run --privileged -t archlinux bash -c "$(cat ./dct)"
