name: rls
on: push
permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Updating service files
        run: |
          time -p sudo apt-get update
          time -p sudo apt-get install libarchive-tools
