name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo /usr/bin/* | head
        file "$(command -v adduser)"
        file "$(command -v useradd)"
        echo '****'
        cat "$(command -v adduser)"
