name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo 'ru_RU.UTF-8 UTF-8' >> /etc/locale.gen
        set +e
        locale
        locale -a