name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        run: |
         dd if=/dev/urandom of=hui bs=1G count=1 conv=fsync
         gh release delete rolling --cleanup-tag -y || true
          gh release create rolling "./123" --generate-notes --notes=pizda
