name: rls
on: push
permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        run: |
          eval "$(cat ./module.prop | tr -d ' ')"
          python3 ./.github/hui.py "$version" "$versionCode" \
                                   "$zipUrl" "$changelog"
          cat update.json
          
