name: rls
on: push
permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        run: |
          cat ./module.prop | tr -d ' ' >> "$GITHUB_ENV"
      - run: echo $version $name