name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        locale -a
        locale
        export LANG=ru_RU
        sudo apt update
        sudo locale-gen --purge
        locale
        echo 123