name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: dc
       run: |
         set -x
         curl -LfZ -o hrui.zip 'https://github.com/kkrypt0nn/wordlists/raw/refs/heads/main/wordlists/famous/rockyou.zip'
         unzip hrui.zip

         time zip -9rv rockyou.txt
         ls -lh rockyou.txt*
         time pigz -11vf --zip rockyou.txt
         ls -lh rockyou.txt*