name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: ckout
       uses: actions/checkout@v4
     - name: dc
       run: |
         docker pull archlinux
         sudo docker run --privileged -t archlinux touch hui
         sudo find /var/lib/docker/overlay2 -type f -name '*.iso' 2> /dev/null
#     - name: rls
#       run: |
#         gh release delete iso --cleanup-tag -y || true
#         gh release create iso /out/*.iso
#       env:
#         GH_TOKEN: ${{ github.token }}
