name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
         gh release delete rolling --cleanup-tag -y || true
          gh release create rolling "./123" --generate-notes --notes=pizda
