name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: tar -cvf - ./* | lz4 -c -6 > ./njk.tar.lz4
      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(sha256sum ./njk.tar.lz4 | cut -d ' ' -f1)"
          gh release delete rolling -y
          gh release create rolling "./njk.tar.lz4#${sha}.sha256" --generate-notes
