name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        locale
        export LANG=en_US.UTF-8
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo apt update
        locale
        echo абв