name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          file hui.c
          gcc hui.c -o huih
          chmod +x huih
          file huih*
          echo '****'
          cat huih
      - run: |
          time -p ./huih
          time -p python3 ./huih.py
          time -p bash ./huih.sh