name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: hui
        run: |
          dd if=/dev/urandom of=./zx bs=1G count=1 conv=fsync
          time -p openssl sha256 ./zx
          time -p python3 ./hui.py
