name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          time -p sudo dd if=/dev/zero of=/dev/shm/hui bs=4K count=1048576
          time -p sudo sh -c 'dd if=/dev/zero bs=4K count=1048576 > /dev/shm/hui'