name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: ckout
       uses: actions/checkout@v4
     - name: dc
       run: |
         docker pull archlinux
         sudo docker run --name archiso -dt --privileged archlinux
         sudo docker cp ./dct archiso:/
         docker exec archiso bash ./dct
         sudo docker cp archiso:/out/archlinux-baseline-1-x86_64.iso .
     - name: rls
       run: |
         gh release delete iso --cleanup-tag -y || true
         gh release create iso ./archlinux-baseline-1-x86_64.iso
       env:
         GH_TOKEN: ${{ github.token }}
