name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - run: |
        locale
        export LANG=ru_RU.UTF-8
        sudo locale-gen --purge --lang ru_RU.UTF-8
        sudo apt update
        locale
        echo 123