name: rls
on: push
permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        run: |
          cat ./module.prop | tee -a "$GITHUB_ENV"
      - run: echo $version $name
      - run: |
          zip -rv9 hui ./* -x \
          module.prop
      - run: cat -A module.prop changelog.md
