name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: dc
       run: |
         sudo apt update
         sudo apt install xfsprogs

         sudo bash ./huih.sh
         
