name: RLS
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: ckout
       uses: actions/checkout@v4
     - name: dc
       run: |
         curl -fZ -o hrui.zip 'https://github.com/kkrypt0nn/wordlists/raw/refs/heads/main/wordlists/famous/rockyou.zip'
         unzip hrui.zip

         sudo apt update
         sudo apt install pigz
         time zip -9rv hrui
         ls -lh hrui.zip
         time pigz -11vf --zip hrui
         ls -lh hrui.zip