name: mkng

on:
  push:
    branches: [main]
jobs:
  cmprsng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mkng n fle
        run: |
          tar -cvf ./rch-nstll.tar ./*
          zstd --ultra -20 ./rch-nstll.tar
      - name: rlsng
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add rch-nstll.zst
          git commit -m 'hui'
          git push
