name: rls
on: push
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating service files
        shell: python
        run:
          import json
          hui = {
              "z": "v",
              "o": 123
          }
          print(json.dumps(hui))