name: JSON generate
on:
  schedule:
  - cron: '00 0,6,12,18 * * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: apktool
          version: 1.0
      - run: bash ./jsongen.sh
