name: JSON generate
on:
  push
  schedule:
  - cron: "*/1 * * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: apktool
          version: 1.0

      - name: Run script
        run: bash ./jsongen.sh
